import type { NextPage } from 'next'
import Head from 'next/head';
import Navbar from '../components/Home/Navbar'
import styles from '../styles/Home.module.scss'
import Banner from './../components/Home/Banner';
import Transactions from './../components/Home/Transactions';
import Footer from './../components/Home/Footer';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dapp-t </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>
      <Banner/>
      <Transactions/>
      <Footer/>
    </div>
  )
}

export default Home
